name: build

on:
  push:
    branches:
      - build  # Set a branch that will trigger a deployment
  schedule:
        # Runs everyday at 8:00 AM
        - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/build' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_DIR: ./docs
          commit_message: ${{ github.event.head_commit.message }}
